version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q123
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  ads:
    container_name: ads
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    volumes:
      - ads:/usr/src/ads/
    depends_on:
      - database
    networks:
      - backend

volumes:
  ads:
  postgres:

networks:
  backend:
    driver: bridge